### ISSUE TITLE
DCAF Code Coverage

### ISSUE THREAD

**Issue by Jay-study-nildana** [Jay-study-nildana/Azure-CSharp-Corp-Trainer-Syllabus#78]
Measure the code coverage of your tests to ensure that a significant portion of your codebase is tested.

```
name: CI and Deploy Azure Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test --no-restore --verbosity normal

    - name: Code Coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Publish Code Coverage Results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: '**/coverage.cobertura.xml'

    - name: Static Code Analysis
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Run Static Code Analysis
      run: dotnet sonarscanner begin /k:"YourProjectKey" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" 
    - run: dotnet build
    - run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions'
      uses: azure/functions-action@v1
      with:
        app-name: DCComicsMar62025
        package: './publish'
```
